language: generic

dist: trusty
sudo: required

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
  - sudo apt-get -qq update
  - sudo apt-get install qt59-meta-minimal

script:
  - .ci/test

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-6
      - clang-5.0
      - libstdc++6
  env:
    - MATRIX_EVAL="CC=g++-6 && CXX=g++-6"

