#!/usr/bin/env bash

set -e
set -x

if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
  # This will set up our environment to use the freshly-installed
  # QT 5.9 PPA packages
  set +e
  source /opt/qt59/bin/qt59-env.sh
  set -e

  qmake -v
  qmake "CONFIG+=test" "QMAKE_CXX=g++-6" "QMAKE_LINK=g++-6" -spec linux-g++  amanuensis.pro
  make
  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${TRAVIS_BUILD_DIR}/core" core-test/core-test
elif [[ $TRAVIS_OS_NAME == 'osx' ]]; then
  qmake -v
  qmake "CONFIG+=test" -spec macx-clang amanuensis.pro
  make

  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${TRAVIS_BUILD_DIR}/core" core-test/core-test && \
  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${TRAVIS_BUILD_DIR}/trusty" trusty-test/trusty-test

else
  echo "Unrecognized OS name $TRAVIS_OS_NAME; cannot continue."
  exit 1
fi
